name: Dev Container Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - 1.0.0*
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/trolie/spec-devcontainer
          cacheFrom: ghcr.io/trolie/spec-devcontainer
          push: always
          subFolder: .github
